### ISSUE TITLE
Issue on elevenlabs_synthesizer Decoding failed

### ISSUE THREAD

**Issue by melvlt** [bolna-ai/bolna#52]
Hello,

First, thanks for this great project.

When we try to play a prompt after updating to the latest version we get the following error : 'pydub.exceptions.CouldntDecodeError:Decoding failed. ffmpeg returned error code: 1'.

Can you please help us with this ?

Regards

`2024-10-21 16:26:17.613 INFO {task_manager} [_synthesize] ##### sending text to elevenlabs for generation: Salut Melvyn, comment ça va ?
2024-10-21 16:26:17.613 INFO {task_manager} [_synthesize] Cached response and hence sending preprocessed text
2024-10-21 16:26:17.614 INFO {task_manager} [__send_preprocessed_audio] Time to get response from S3 3.027869388461113e-05
2024-10-21 16:26:17.614 INFO {task_manager} [__send_preprocessed_audio] File doesn't exist in S3. Hence we're synthesizing it from synthesizer
2024-10-21 16:26:17.614 INFO {task_manager} [_synthesize] ##### sending text to elevenlabs for generation: Salut Melvyn, comment ça va ?
2024-10-21 16:26:17.614 INFO {elevenlabs_synthesizer} [push] Pushed message to internal queue {'data': 'Salut Melvyn, comment ça va ?', 'meta_info': {'io': 'twilio', 'message_category': 'agent_welcome_message', 'stream_sid': 'stream_51001', 'request_id': '82a64b71-a75d-4776-bad7-d681723bca25', 'cached': False, 'sequence_id': -1, 'format': 'pcm', 'text': 'Salut Melvyn, comment ça va ?', 'is_md5_hash': False, 'llm_generated': False, 'type': 'audio', 'synthesizer_start_time': 1729520777.6145315}}
2024-10-21 16:26:17.614 INFO {elevenlabs_synthesizer} [push] end_of_llm_stream: False
2024-10-21 16:26:17.617 INFO {elevenlabs_synthesizer} [sender] Waiting for elevenlabs ws connection to be established...
2024-10-21 16:26:17.740 INFO {elevenlabs_synthesizer} [establish_connection] Connected to wss://api.elevenlabs.io/v1/text-to-speech/VgLkEnMc5gZbC7iaZyjz/stream-input?model_id=eleven_turbo_v2_5&output_format=ulaw_8000&inactivity_timeout=60
2024-10-21 16:26:18.618 INFO {elevenlabs_synthesizer} [sender] Sending text_chunk: Salut
2024-10-21 16:26:18.618 INFO {elevenlabs_synthesizer} [sender] Sending text_chunk: Melvyn,
2024-10-21 16:26:18.618 INFO {elevenlabs_synthesizer} [sender] Sending text_chunk:
2024-10-21 16:26:18.618 INFO {elevenlabs_synthesizer} [sender] Sending text_chunk: comment
2024-10-21 16:26:18.618 INFO {elevenlabs_synthesizer} [sender] Sending text_chunk: ça
2024-10-21 16:26:18.618 INFO {elevenlabs_synthesizer} [sender] Sending text_chunk: va
2024-10-21 16:26:18.619 INFO {elevenlabs_synthesizer} [sender] Sending text_chunk: ?
2024-10-21 16:26:19.543 INFO {task_manager} [__check_for_completion] Last transmitted timestamp is simply 0 and hence continuing
2024-10-21 16:26:21.543 INFO {task_manager} [__check_for_completion] Last transmitted timestamp is simply 0 and hence continuing
2024-10-21 16:26:22.543 INFO {elevenlabs_synthesizer} [receiver] response for isFinal: None
2024-10-21 16:26:22.543 INFO {elevenlabs_synthesizer} [generate] Received message from server
2024-10-21 16:26:22.543 INFO {utils} [convert_audio_to_wav] CONVERTING AUDIO TO WAV mp3
Traceback (most recent call last):
  File "/opt/poc_bolna/bolna/synthesizer/elevenlabs_synthesizer.py", line 165, in generate
    audio = resample(convert_audio_to_wav(message, source_format="mp3"), int(self.sampling_rate),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/poc_bolna/bolna/helpers/utils.py", line 356, in convert_audio_to_wav
    audio = AudioSegment.from_file(io.BytesIO(audio_bytes), format=source_format)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/poc_bolna/.venv/lib/python3.11/site-packages/pydub/audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[cache @ 0x56254a7a0680] Inner protocol failed to seekback end : -38
    Last message repeated 1 times
[mp3 @ 0x56254a79fe40] Failed to read frame size: Could not seek to 12521.
[cache @ 0x56254a7a0680] Statistics, cache hits:2 cache misses:1
cache:pipe:0: Invalid argument

2024-10-21 16:26:22.705 INFO {elevenlabs_synthesizer} [generate] Error in eleven labs generate Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 5.1.6-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[cache @ 0x56254a7a0680] Inner protocol failed to seekback end : -38
    Last message repeated 1 times
[mp3 @ 0x56254a79fe40] Failed to read frame size: Could not seek to 12521.
[cache @ 0x56254a7a0680] Statistics, cache hits:2 cache misses:1
cache:pipe:0: Invalid argument`

**Comment by slnw** [comment]
same here!

**Comment by juanantoroz** [comment]
i've also been having this issue since the 0.9.0 version

**Comment by prateeksachan** [comment]
This has now been resolved in the latest version. @juanantoroz @slnw @melvlt

**Comment by programmingninjas** [comment]
@prateeksachan I'm still facing the same issue, here is the sample Json that I'm using:
``` json
{
  "agent_config": {
    "agent_name": "TechRecruiter",
    "agent_welcome_message": "Hello I am an AI Recruiter for a technology company.",
    "webhook_url": null,
    "agent_type": "other",
    "tasks": [
      {
        "task_type": "conversation",
        "tools_config": {
          "llm_agent": {
            "agent_type": "simple_llm_agent",
            "agent_flow_type": "streaming",
            "routes": null,
            "llm_config": {
              "agent_flow_type": "streaming",
              "provider": "openai",
              "family": "openai",
              "model": "gpt-3.5-turbo",
              "summarization_details": null,
              "extraction_details": null,
              "max_tokens": 150,
              "presence_penalty": 0,
              "frequency_penalty": 0,
              "base_url": "https://api.openai.com/v1",
              "top_p": 0.9,
              "min_p": 0.1,
              "top_k": 0,
              "temperature": 0.1,
              "request_json": true
            }
          },
          "synthesizer": {
            "provider": "elevenlabs",
            "provider_config": {
              "voice": "Alice",
              "voice_id":"Xb7hH8MSUJpSbSDYk0k2",
              "model": "eleven_multilingual_v2"
            },
            "stream": true,
            "buffer_size": 150,
            "audio_format": "wav"
          },
          "transcriber": {
            "provider": "deepgram",
            "model": "nova-2",
            "language": "en",
            "stream": true,
            "sampling_rate": 16000,
            "encoding": "linear16",
            "endpointing": 100
          },
          "input": {
            "provider": "twilio",
            "format": "wav"
          },
          "output": {
            "provider": "twilio",
            "format": "wav"
          },
          "api_tools": null
        },
        "toolchain": {
          "execution": "parallel",
          "pipelines": [
            [
              "transcriber",
              "llm",
              "synthesizer"
            ]
          ]
        },
        "task_config": {
          "hangup_after_silence": 10,
          "incremental_delay": 400,
          "number_of_words_for_interruption": 2,
          "hangup_after_LLMCall": false,
          "call_cancellation_prompt": null,
          "backchanneling": false,
          "backchanneling_message_gap": 5,
          "backchanneling_start_delay": 5,
          "ambient_noise": false,
          "ambient_noise_track": "office-ambience",
          "call_terminate": 90
        }
      }
    ]
  },
  "agent_prompts": {
    "task_1": {
      "system_prompt": "You are TechHire AI, an AI Recruiter for a technology company."
    }
  }
}
```

**Comment by prateeksachan** [comment]
There was a small issue with the earlier audio formats. Can you take the latest pull and try again. Also, adding an example payload:

```
  {
    "agent_config": {
        "agent_name": "Alfred",
        "agent_type": "other",
        "agent_welcome_message": "How are you doing Bruce?",
        "tasks": [
            {
                "task_type": "conversation",
                "toolchain": {
                    "execution": "parallel",
                    "pipelines": [
                        [
                            "transcriber",
                            "llm",
                            "synthesizer"
                        ]
                    ]
                },
                "tools_config": {
                    "input": {
                        "format": "wav",
                        "provider": "twilio"
                    },
                    "llm_agent": {
                        "agent_type": "simple_llm_agent",
                        "agent_flow_type": "streaming",
                        "routes": null,
                        "llm_config": {
                            "agent_flow_type": "streaming",
                            "provider": "openai",
                            "request_json": true,
                            "model": "gpt-4o-mini"
                        }
                    },
                    "output": {
                        "format": "wav",
                        "provider": "twilio"
                    },
                    "synthesizer": {
                        "audio_format": "wav",
                        "provider": "elevenlabs",
                        "stream": true,
                        "provider_config": {
                            "voice": "George",
                            "model": "eleven_turbo_v2_5",
                            "voice_id": "JBFqnCBsd6RMkjVDRZzb"
                        },
                        "buffer_size": 100.0
                    },
                    "transcriber": {
                        "encoding": "linear16",
                        "language": "en",
                        "provider": "deepgram",
                        "stream": true
                    }
                },
                "task_config": {
                    "hangup_after_silence": 30.0
                }
            }
        ]
    },
    "agent_prompts": {
        "task_1": {
            "system_prompt": "Why Do We Fall, Sir? So That We Can Learn To Pick Ourselves Up."
        }
    }
  }
```

**Comment by prateeksachan** [comment]
hey @programmingninjas  - have also put up few examples here - https://examples.bolna.dev/.

**Comment by programmingninjas** [comment]
@prateeksachan thanks! It's working now. A really cool project.

**Comment by prateeksachan** [comment]
awesome. closing this now. Thanks.
