### ISSUE TITLE
error in executing 'routes'

### ISSUE THREAD

**Issue by ashok-groovy** [bolna-ai/bolna#85]
bolna-app-1   | Traceback (most recent call last):
bolna-app-1   |   File "/app/quickstart_server.py", line 90, in websocket_endpoint
bolna-app-1   |     async for index, task_output in assistant_manager.run(local=True):
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/agent_manager/assistant_manager.py", line 41, in run
bolna-app-1   |     task_manager = TaskManager(self.agent_config.get("agent_name", self.agent_config.get("assistant_name")),
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/agent_manager/task_manager.py", line 275, in __init__
bolna-app-1   |     if self.kwargs['routes']:
bolna-app-1   | KeyError: 'routes'
bolna-app-1   | 2024-12-04 20:28:14.597 ERROR {quickstart_server} [websocket_endpoint] error in executing 'routes'

**Comment by programmingninjas** [comment]
@prateeksachan @ashok-groovy I'm facing the same error, is there any workaround for this?

**Comment by ashok-groovy** [comment]
Yes, Just remove routes from the json,

and add  "routes": null,

**Comment by programmingninjas** [comment]
@ashok-groovy Thank You Ashok! But what if we want semantic routing?

**Comment by prateeksachan** [comment]
Hi @programmingninjas you nay use this payload for `routes`.

Additionally, I'm looking for a way to have multiple different payload for different kind of agents. I thought about utilizing Github's wiki - but it's not good. If you know any easy-to-setup and low maintenence alternative please do let me know!
