### ISSUE TITLE
elevenlabs_synthesizer

### ISSUE THREAD

**Issue by ashok-groovy** [bolna-ai/bolna#87]
bolna-app-1   | 2024-12-05 11:46:41.902 INFO {elevenlabs_synthesizer} [receiver] response for isFinal: None
bolna-app-1   | 2024-12-05 11:46:41.903 INFO {elevenlabs_synthesizer} [generate] Received message from server
bolna-app-1   | 2024-12-05 11:46:41.903 INFO {utils} [convert_audio_to_wav] CONVERTING AUDIO TO WAV mp3
bolna-app-1   | Traceback (most recent call last):
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/synthesizer/elevenlabs_synthesizer.py", line 174, in generate
bolna-app-1   |     audio = resample(convert_audio_to_wav(message, source_format="mp3"), int(self.sampling_rate),
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/bolna/helpers/utils.py", line 357, in convert_audio_to_wav
bolna-app-1   |     audio = AudioSegment.from_file(io.BytesIO(audio_bytes), format=source_format)
bolna-app-1   |   File "/usr/local/lib/python3.10/site-packages/pydub/audio_segment.py", line 773, in from_file
bolna-app-1   |     raise CouldntDecodeError(
bolna-app-1   | pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

**Comment by prateeksachan** [comment]
@ashok-groovy this shouldn't be occuring now. Can you please check and let me know in case this is still an issue.
